# Generated by Django 3.2.5 on 2021-07-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_delete_moringamerch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
